# bitbucket-pipelines.yml - Bitbucket Pipelines configuration
# Copyright (C) 2016-2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.

# See <https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html>
# for details.
---
definitions:
  steps:
    - step: &test
        name: Test step
        caches:
          - pip
        script:
          - pip install setuptools
          - python ./setup.py test
image: python:3
pipelines:
  default:
    - step: *test
  branches:
    # Overrides the default pipeline.
    deployment:
      - step:
          script:
            - ": nothing"
  bookmarks:
    deployment/*:
      - step:
          deployment: test
          script:
            - pipe: atlassian/pypi-publish:0.2.4
              variables:
                PYPI_USERNAME: $TESTPYPI_USERNAME
                PYPI_PASSWORD: $TESTPYPI_PASSWORD
                REPOSITORY: https://test.pypi.org/legacy/
    deployment/staging:
      - step:
          deployment: staging
          caches:
            - pip
          script:
            - pip install setuptools twine
            - python ./setup.py sdist bdist_wheel
          artifacts:
            - dist/*
