# bitbucket-pipelines.yml - Bitbucket Pipelines configuration
# Copyright (C) 2016-2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.

# See <https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html>
# for details.
---
definitions:
  steps:
    - step: &test
        name: Test
        caches:
          - pip
        script:
          - pip install "setuptools>=38.6"
          - python ./setup.py test
    - step: &deploy-pypi
        name: PyPI deployment
        deployment: production
        script:
          - pipe: atlassian/pypi-publish:0.2.5
            variables:
              PYPI_USERNAME: $PYPI_USERNAME
              PYPI_PASSWORD: $PYPI_PASSWORD
              DISTRIBUTIONS: sdist bdist_wheel
    - step: &deploy-testpypi
        name: TestPyPI deployment
        deployment: test
        script:
          - pipe: atlassian/pypi-publish:0.2.5
            variables:
              PYPI_USERNAME: $TESTPYPI_USERNAME
              PYPI_PASSWORD: $TESTPYPI_PASSWORD
              DISTRIBUTIONS: sdist bdist_wheel
              REPOSITORY: https://test.pypi.org/legacy/
image: python:3
pipelines:
  branches:
    default:
      - step: *test
  bookmarks:
    deployment/test:
      - step: *deploy-testpypi
    deployment/staging:
      - step:
          name: Version check
          script:
            - python ./setup.py --version | grep -v '\.dev[0-9]'
      - step:
          <<: *deploy-pypi
          deployment: staging
    deployment/production:
      - step:
          name: Version check
          script:
            - python ./setup.py --version | grep -v '\.dev[0-9]'
      - step:*deploy-pypi
